
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 07 17:05:59 CST 2016
//----------------------------------------------------

package practica1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERV = 22;
  public static final int PORC = 2;
  public static final int OR = 4;
  public static final int LETRA = 27;
  public static final int CORC = 21;
  public static final int CM = 9;
  public static final int CORA = 20;
  public static final int SIMPLE = 11;
  public static final int BLANCO = 14;
  public static final int ERROR = 23;
  public static final int FLECHA = 18;
  public static final int RETORNO = 13;
  public static final int PARC = 26;
  public static final int ID = 28;
  public static final int PARA = 25;
  public static final int POR = 5;
  public static final int PT = 3;
  public static final int DSPT = 17;
  public static final int PTCM = 19;
  public static final int EOF = 0;
  public static final int CARRO = 24;
  public static final int DOBLE = 12;
  public static final int CONJ = 16;
  public static final int TODO = 15;
  public static final int error = 1;
  public static final int CAD = 29;
  public static final int SALTO = 10;
  public static final int INTER = 7;
  public static final int RANGO = 8;
  public static final int MAS = 6;
}

